targets:
  $default:
    builders:
      raw_representable_generator:
        enabled: true

builders:
  raw_representable_generator:
    import: "package:flutter_template/util/generator/builder.dart"
    builder_factories: ["builder"]
    build_extensions: {".dart": ["raw_representable_generator.g.part"]}
    auto_apply: all_packages
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]